name: Maintenance
version: ${version}
main: eu.kennytv.maintenance.spigot.MaintenanceSpigotBase
author: kennytv
description: ${description}
softdepend: [ProtocolLib, ServerListPlus, ProtocolSupport, LuckPerms]
website: https://www.spigotmc.org/resources/maintenance.40699/
api-version: 1.13

commands:
  maintenance:
    description: Maintenance main-command
    aliases: [maintenancespigot, mt]
    permission: maintenance.command