name: Maintenance
version: ${version}
main: eu.kennytv.maintenance.spigot.MaintenanceSpigotBase
author: kennytv
description: ${description}
softdepend: [ProtocolLib, ServerListPlus, ProtocolSupport, LuckPerms]
website: https://hangar.papermc.io/kennytv/Maintenance
api-version: 1.13

commands:
  maintenance:
    description: Maintenance main-command
    aliases: [mt]
    permission: maintenance.command