name: MaintenanceSpigot
version: ${project.version}
main: eu.kennytv.maintenance.spigot.MaintenanceSpigotBase
author: KennyTV
description: Enable maintenance mode with a custom maintenance motd and icon.
softdepend: [ProtocolLib, ServerListPlus, ProtocolSupport]
website: https://www.spigotmc.org/resources/maintenance.40699/
api-version: 1.13

commands:
  maintenance:
    description: Maintenance main-command
    aliases: [maintenancespigot]