name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MaintenanceFiles
          path: |
            **/Maintenance.jar
            **/MaintenanceSpigot.jar
            **/MaintenanceBungee.jar
            **/MaintenanceVelocity.jar
            **/MaintenanceSponge.jar
